In [1]:
import numpy as np #Kütüphaneyi kullanabilmek için import etmeliyiz.

In [2]:
benimListem = [20,30,40]

In [4]:
type (benimListem) #Veri tipiniöğrenmek için type kullanılır

list

In [5]:
np.array(benimListem) #python listesini numpy dizisine dönüştürmek için np.array kullanılır.

array([20, 30, 40])

In [6]:
matrixListesi = [[10,20,30], [40,50,60], [70,80,90]]

In [8]:
matrixListesi [1] #1.satırı listeler

[40, 50, 60]

In [10]:
matrixListesi[1][0]#1.satırın 0.elemanını listeler

40

In [ ]:
np.array(matrixListesi)#matrixListesi'ni diziye dönüştürür.

# arange

In [13]:
range (0,10) #başlangıç ve bitiş değeri belli adım sayısı verilmezse varsayılan olarak 1 alınır

range(0, 10)

In [14]:
list(range (0,10)) #range() fonksiyonunu kullanarak bir sayı aralığındaki değerleri içeren bir liste oluşturur

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10) #0'dan 10'a kadar numpy dizisi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2) #0'dan 10'a kadar 2 şer atlayarak dizi oluşturur. (step size)

array([0, 2, 4, 6, 8])

In [21]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

# Zeros and ones

In [22]:
np.zeros(6) #içerisinde 6 tane 0 olan bir dizi oluşturuyor.

array([0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [26]:
np.linspace(0,10,5) #0 ile 10 arasında eşit aralıklı 5 sayı

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## eye

In [27]:
np.eye(10) #Birim matris, köşegeni 1 olan ve geri kalan tüm elemanları sıfır olan kare matristir.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [28]:
np.random.randn(8)

array([ 1.68932653,  0.08204425, -1.92427993,  1.53398051, -0.34725463,
        1.52793056,  1.19308286, -1.636902  ])

In [29]:
np.random.randn(2,2)

array([[ 0.67231222,  0.39317972],
       [-0.24262489,  0.50511931]])

In [30]:
np.random.randint(1,10)

3

In [31]:
np.random.randint(5)

1

In [32]:
np.random.randint(1,10,5) #1'den 10'a kadar 5 tane random integer değer döndürür

array([4, 2, 4, 3, 7])

In [33]:
numpyDizim = np.arange(20)

In [37]:
numpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## numpy dizi methodları

In [35]:
numpyDizim.reshape(5,4) #reshape ile diziyi istediğim şekilde ayırabilirim.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
numpyDizim.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
numpyDizim.max()

19

In [39]:
numpyDizim.min()

0

In [40]:
numpyDizim.argmax()

19

In [41]:
reshapeDizim = numpyDizim.reshape(4,5)

In [43]:
reshapeDizim.shape #Güncel dizimin hangi şekle sahip olduğunu öğrenebilirim.

(4, 5)

## Numpy indeksler

In [44]:
benimDizim = np.arange(0,15)

In [45]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
benimDizim[5]

5

In [48]:
benimDizim[3:8] #Dizin 3'ten 8'e kadar elemanlarını listeler.

array([3, 4, 5, 6, 7])

In [51]:
benimDizim[3:8] = -7 #3'ten 8'e kadar indekslerin değerine -7 atar.

In [52]:
benimDizim

array([ 0,  1,  2, -7, -7, -7, -7, -7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
ikinciDizi= np.arange(0,24) #ikinciDizi isminde 0'dan 24'e bir dizi oluştur.

In [54]:
ikinciDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
slicingDizisi = ikinciDizi[4:9] #ikinciDizi dizisinin 4ten 9a kadar olan indekseleri slicingDizisi adında yeni bir dizi oluşturur.

In [72]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [73]:
ikinciDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [78]:
slicingDizisi[:] = 700 #slicingDizisinin elemanlarını 700'e esitler

In [79]:
slicingDizisi #Yeni slicingDizisi

array([700, 700, 700, 700, 700])

In [80]:
ikinciDizi #Yeni ikinciDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [81]:
ucuncuDizi = np.arange(0,24) #ucuncuDizi adında 0'dan 24'e bir dizi oluşturdum

In [83]:
ucuncuDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
ucuncuDiziKopya = ucuncuDizi.copy() #ucuncuDizi dizisini kopyasını oluşturdum

In [86]:
ucuncuDiziKopya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [87]:
ucuncuDiziKopyaSlicing = ucuncuDiziKopya[3:6] #slicin işlemi yapıldı

In [89]:
ucuncuDiziKopyaSlicing[:] = 800

In [90]:
ucuncuDiziKopyaSlicing

array([800, 800, 800])

In [91]:
ucuncuDiziKopya

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [92]:
ucuncuDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# matrix indeksler

In [93]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]] #bir liste oluşturur

In [94]:
matrixDizim = np.array (benimListem) #bu listeyi matris dizinine dönüştürür

In [95]:
matrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [99]:
matrixDizim[0] #matris dizinin 0. satırı

array([10, 20, 30])

In [101]:
matrixDizim[2][1]

50

## operasyonlar

In [107]:
yeniDizi = np.random.randint(1,100,20) #yeniDizi adında 1den 100e kadar 20 adet random sayılardan oluşan 

In [108]:
yeniDizi

array([19, 55, 37, 56, 99, 50, 32, 38, 75, 27, 25, 67, 64, 87, 43, 76, 66,
       34, 19, 59])

In [109]:
yeniDizi >24 #olusturulan yeniDizideki sayılar 24'ten büyük ise true değilse false değerini dönderecektir

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [111]:
sonucDizisi = yeniDizi > 24

In [112]:
sonucDizisi

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [115]:
yeniDizi

array([19, 55, 37, 56, 99, 50, 32, 38, 75, 27, 25, 67, 64, 87, 43, 76, 66,
       34, 19, 59])

In [124]:
yeniDizi[sonucDizisi] #sadece trueları listeliyor

array([55, 37, 56, 99, 50, 32, 38, 75, 27, 25, 67, 64, 87, 43, 76, 66, 34,
       59])

In [125]:
sonDizi = np.arange(0,24)

In [126]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [127]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [128]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])